[font]
size = 10.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
